fix: after_script of the deploy job

diff --git a/.github/workflows/stage_1.yaml b/.github/workflows/stage_1.yaml
--- a/.github/workflows/stage_1.yaml
+++ b/.github/workflows/stage_1.yaml
@@ -37,6 +37,10 @@ jobs:
           username: ${{ secrets.SSH_USER }}
           private_key: ${{ secrets.SSH_KEY }}
           scp_source: ./stage_1/docker-stack.yml
-          scp_target: ~/apps/hng12/
+          scp_target: ~/apps/hng12/stage-1-stack.yml
           after_script: |
-            docker stack deploy -c ~/apps/hng12/stage-1-stack.yml hng-12-stage-1
+            docker stack deploy -c ~/apps/hng12/docker-stack.yml hng-12-stage-1
+            if [ $? -ne 0 ]; then
+              echo "Docker stack deploy failed!"
+              exit 1
+            fi
